Webhook: "" # here your discord webhook
Embed: # Placeholders: %player%, %wingroup%, %casetype%, %animation%, %casetitle%.
  Title: "DonateCase, opening case:"
  Description: ""
  Color:
    r: 43
    g: 45
    b: 49
  Footer:
    Text: "DCWebHook | Addon for DonateCase"
    Icon: "https://cdn.discordapp.com/icons/860809265689788447/3031feb820fd76cdaffd2a86dc7a12f3.png"
  Author:
    Name: ""
    Url: ""
    Icon: ""
  Fields:
    field1:
      Title: ""
      Value: "**Player:** %player%"
      Inline: false
    field2:
      Title: ""
      Value: "**Type:** %casetype%"
      Inline: false
    field3:
      Title: ""
      Value: "**Prize:** %wingroup%"
      Inline: false
